# frozen_string_literal: true

source "https://rubygems.org"

gem "rails", "~> 8.0"
gem "nquery", path: ".."
gem "sqlite3", "~> 2.0"
gem "puma", ">= 7.2.1", "< 8"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "propshaft"
gem "bcrypt", "~> 3.1"

group :development, :test do
  gem "debug"
  gem "rspec-rails", "~> 7.0"
  gem "capybara", "~> 3.40"
  gem "selenium-webdriver", "~> 4.0"
end
